build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  only:
    refs:
      - tags
  except:
    - branches
  script:
    - mkdir -p /kaniko/.docker
    - touch /kaniko/.docker/config.json && chmod 0600 /kaniko/.docker/config.json
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n ${DOCKERHUB_USERNAME}:${DOCKERHUB_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $DOCKERHUB_IMAGE:$CI_COMMIT_TAG --destination $DOCKERHUB_IMAGE:latest
