name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Log into docker registry
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        username: ${{ vars.REGISTRY_USER }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - uses: actions/checkout@v3
# TODO: Use tags instead
    - name: Build the Docker image
      run: |
        docker build -f Dockerfile -t chorusab/fsh-fhir-build-image:"0.9.$(date +%s)" -t chorusab/fsh-fhir-build-image:latest .
    - name: Push the Docker image
      run: |
        docker push chorusab/fsh-fhir-build-image
